baseurl = "http://www.superoo7.com"
title = "superoo7"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]
[services.disqus]
disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Johnson Lai"
  info = "Crypto x AI"
  description = "Johnson · Crypto x AI"
  keywords = "blog,developer,personal"
  avatarurl = "images/joker.jpg"
  info_details = "Head of Data & AI @ Chromia\n\nAdvisor @ ChasmNetwork\n\nPrev: CoinGecko"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"
  touchicon = "/img/apple-touch-icon.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCss = ["css/custom.css"]
  customSCSS = ["scss/custom.scss", "scss/homepage.scss"]
  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/superoo7/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/jlwhoo7/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/superoo7/"

# Analytics
[params.goatCounter]
  code = "superoo7"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

  